### ISSUE TITLE
Thank you, but could you please provide an example

### ISSUE THREAD

**Issue by Sue-Fwl** [Husseinjd/ArSEL#1]
Greetings,

Thanks alot for making your work available for other researchers it's really appreciated.

I would like to ask if possible to provide an example of usage, because although there are helpful comments for each methodology -very thankful-, an example would be of a great help to explore the possibilities and outcomes before investing time in understanding the classes.

Thanks in advance,

P.S I've already read the paper.

**Comment by Husseinjd** [comment]
Hello, 

Please check the jupyter notebook in the repo  (Arsel_Notebook.ipynb) it should contain the example you are looking for :). 

Best,

**Comment by Sue-Fwl** [comment]
> Hello,
> 
> Please check the jupyter notebook in the repo (Arsel_Notebook.ipynb) it should contain the example you are looking for :).
> 
> Best,

Thanks alot for replying, I checked the notebook but it only uses the main function "get_emotional_score" on an already transliterated word without demonstrating the previous step of transliteration using Buckwalter and POS tagging.
So I checked out all the files and it looked to me that there is no file for an Ar to Buckwalter transliteration, only found 'buckwalter.py' that process an already transliterated sentence.

Would it be possible to provide the code of the transliteration? Because not all implementations give the same results.

With appreciation,

**Comment by Husseinjd** [comment]
Hello, 

Please check the MADAMIRA tool for the transliteration to Buckwalter form from arabic text after.

Paper: https://www.aclweb.org/anthology/L14-1479/
Tool : http://innovation.columbia.edu/technologies/cu14012_arabic-language-disambiguation-for-natural-language-processing-applications

**Comment by Sue-Fwl** [comment]
Appreciate it! Will check it.
